### ISSUE TITLE
Confusion about license for `PropertyGridViewModel.cs`

### ISSUE THREAD

**Issue by Felk** [RolandKoenig/MessageCommunicator#2]
The [LICENSE.md](https://github.com/RolandKoenig/MessageCommunicator/blob/master/LICENSE.md) file in the project's root very licenses the code under MIT, yet the file [`MessageCommunicator.TestGui/_Util/_View/_PropertyGrid/PropertyGridViewModel.cs`](https://github.com/RolandKoenig/MessageCommunicator/blob/master/MessageCommunicator.TestGui/_Util/_View/_PropertyGrid/PropertyGridViewModel.cs) has a dedicated licensing header mentioning `GNU Lesser General Public License`. It looks like that file was just copied from [SeeingSharp2](https://github.com/RolandKoenig/SeeingSharp2). Is the ambiguous licensing situation intended for that file? It makes re-using the `PropertyGrid` code as described in your [blog post](https://www.rolandk.de/wp-posts/2020/08/propertygrid-mit-avalonia/) a bit awkward.

**Comment by RolandKoenig** [comment]
Oh, yes. This is a copy-paste error. Thank you for opening this issue.
I removed the license header from PropertyGridViewModel.cs with commit 01e9be378b8ca4aef11648bc8b14875f45b2e6de
